name: blueprint
description: A blueprint Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  auto_size_text: ^3.0.0
  spider: ^4.2.1
  flutter_riverpod: ^2.4.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  theme_tailor: ^2.0.0
  theme_tailor_annotation: ^2.0.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/vectors/
